// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/silmarsanches/multithreading/config"
	"github.com/silmarsanches/multithreading/internal/infra/services"
	"github.com/silmarsanches/multithreading/internal/useCase"
)

// Injectors from wire.go:

func InitializeCepUseCase(appConfig *config.Config) *useCase.UseCaseGetCep {
	httpExternalServiceViaCep := services.NewHttpExternalServiceViaCep(appConfig)
	httpExternalServiceBrasilApi := services.NewHttpExternalServiceBrasilApi(appConfig)
	useCaseGetCep := useCase.NewUseCaseGetCep(httpExternalServiceViaCep, httpExternalServiceBrasilApi, appConfig)
	return useCaseGetCep
}

// wire.go:

var setUseCaseCepDependency = wire.NewSet(services.NewHttpExternalServiceViaCep, wire.Bind(new(services.ExternalServiceViaCepInterface), new(*services.HttpExternalServiceViaCep)), services.NewHttpExternalServiceBrasilApi, wire.Bind(new(services.ExternalServiceBrasilApiInterface), new(*services.HttpExternalServiceBrasilApi)))
